Docker puppeter change for pdf

diff --git a/services/reports-service/Dockerfile b/services/reports-service/Dockerfile
--- a/services/reports-service/Dockerfile
+++ b/services/reports-service/Dockerfile
@@ -1,10 +1,7 @@
 FROM public.ecr.aws/docker/library/node:22.18.0-trixie-slim
 
-USER root
-
-# Install system dependencies required for Chromium and Puppeteer PDF generation
 RUN apt-get update \
-    && apt-get install -y \
+    && apt-get install -y --no-install-recommends \
         ca-certificates \
         wget \
         gnupg \
@@ -22,23 +19,28 @@ RUN apt-get update \
         libgbm1 \
         libgtk-3-0 \
         libnspr4 \
-        --no-install-recommends \
+        chromium \
+    # Remove vulnerable or unnecessary packages if not required for your app
+    && apt-get purge -y --auto-remove xdg-utils libsndfile1 || true \
+    # Attempt to upgrade only the affected packages (if patched versions are available in the repo)
+    && apt-get install -y --only-upgrade libopenjp2-7 libxslt1.1 \
+    # Clean up
     && rm -rf /var/lib/apt/lists/* \
-    && npm install -g @nestjs/cli pm2@latest puppeteer
+    && npm install -g @nestjs/cli pm2@latest \
+    && rm -vrf /var/cache/apk/*
 
-ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false \
+ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
+    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium \
     NODE_ENV=production
 
 WORKDIR /app
 
-# Copy package files and install dependencies
 COPY ["package.json","./"]
 COPY [".npmrc", "./"]
 RUN --mount=type=secret,id=git_token \
     GITOPS_USER_GITHUB_TOKEN=$(cat /run/secrets/git_token) npm install --legacy-peer-deps --only=production \
-    && rm -f ./.npmrc 
+    && rm -f ./.npmrc
 
-# Copy application source code
 COPY ./src ./src
 COPY ./templates ./templates
 COPY tsconfig.json .
@@ -46,14 +48,10 @@ COPY tsconfig.build.json .
 COPY nest-cli.json .
 COPY entrypoint.sh .
 
-# Build the application
 RUN npm run build
 
-# Expose application port
 EXPOSE 3000
 
-# Ensure script is executable
 RUN chmod +x /app/entrypoint.sh
 
-# Start application
 ENTRYPOINT ["/app/entrypoint.sh"]
